apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # Can be:
  # LoadBalancer (not locally though),
  # ClusterIP (only accessible from inside cluster),
  # NodePort (expose a port externally)
  type: NodePort
  # Defines which pods are served by this service
  # Service becomes a network endpoint for other services or other users to connect to
  # You could also have a nginx application that would then be the LB and route traffic itself?
  selector: # These are and conditions
    app: webapp
  ports:
    - name: http
      port: 80
      targetPort: 80
      # Only for NodePort service types
      # You will replace nodePort with LoadBalancer when deploying in cloud
      nodePort: 30080 # Needs to be > 30,000. O

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  type: NodePort
  selector:
    app: queue
  ports:
    - name: http
      port: 8161
      nodePort: 30010
    - name: endpoint
      port: 61616
      # No nodeport since its internal only
